# Generated by Django 5.2.10 on 2026-02-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_achievement_userachievement_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('cut', 'Cut'), ('bulk', 'Bulk'), ('maintain', 'Maintain')], default='maintain', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
